# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Github Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  gh-pages-deploy-wois:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Clean install dependencies
        run: npm ci
      - name: Run deploy script
        run: git config user.name "bladekaj" && git config user.email "bladekaj@comcast.net"
                  npm run gh-pages-deploy-wois
